### ISSUE TITLE
Issue with opening Waters raw file

### ISSUE THREAD

**Issue by smhjn22** [chhh/IMTBX#3]
I am trying to visualize IM-MS plots obtained on a Waters G2 Si HDMS instrument but the IMTBX-View is unable to open the .raw files. Some of the raw files can be opened, however, I am unable to figure the difference in the files that could cause this. Is there an important file I am missing? Any help would be appreciated. Thanks!
![image](https://user-images.githubusercontent.com/70611585/91917688-a66e9e80-ec8e-11ea-912f-ae6bff5dae02.png)

**Comment by chhh** [comment]
The cause of the error is not clear. Unfortunately this software was written using some new and probably unfinished port of the Waters data access library. I don't work at the lab anymore, and unfortunately can't help you with this one. Even if I could investigate, this would probably boil down to "the library that I have can't read the files you provide properly, need to rewrite parts of it with some older more reliable libraries from Waters". Which I can't do at the momet.
